### ISSUE TITLE
Deleted my save file

### ISSUE THREAD

**Issue by Rokerekor** [Kahmul/SoulsSpeedruns-Save-Organizer#13]
I setup my folders, tried replace save state, it failed, and my save was gone. Maybe warn people to backup saves lol? Dozens of hours of playtime gone in a split second.

**Comment by Kahmul** [comment]
I added a warning that the organizer is not meant for backing up first playthroughs and should be used with care if you do use it for that. As for what caused your issue, I can't tell based on what you said. Lots of speedrunners use the organizer with no issues of that sort, so without reproducible steps I have to assume user error and unfortunately cannot really help or say more than that.
