### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by dominikheinz** [Kahmul/SoulsSpeedruns-Save-Organizer#6]
I am running DarkSouls on linux and I would like to use the Save Organizer on linux too.
Since it is a java application i is cross-platform and should work just fine.

However when I try to run the binary with java it says it could not load the main class.
Could you add a guide on how to the save game organizer on linux?

**Comment by jmateusms** [comment]
I have no knowledge of java, but I just cloned the repo and ran `mvn clean install -B -V`. It compiled without errors.
Backups and restores worked in DS3 (running in Proton/Steam), I haven't tested other games.

The complete set of steps would be:
```
git clone https://github.com/Kahmul/SpeedSouls-Save-Organizer.git
cd SpeedSouls-Save-Organizer
mvn clean install -B -V
```

I don't know if it matters, but I'm in Manjaro Gnome. I installed the following packages using pamac:
- maven (community)
- jdk8 (AUR)

**Comment by iamshell0** [comment]
@dominikheinz were you able to run Save Organizer?

**Comment by masta0f1eave** [comment]
Hey everyone, just want to let you know that method provided by @jmateusms works fine on Ubuntu 20.10, I'm able to run app with DarkSouls 3 via Steam Proton, save/load functions are working.

**Comment by Kahmul** [comment]
The new releases have Linux versions available for download now, so taking the steps mentioned above to build the .jar yourself are no longer necessary.
