### ISSUE TITLE
"Error when trying to load the savefile!" when trying to use it for DS Remastered

### ISSUE THREAD

**Issue by Shini1313** [Kahmul/SoulsSpeedruns-Save-Organizer#7]
I get the Error message in the title when trying to load or create a savestate. This worked fine up until recently. I reinstalled Dark Souls Remastered and Java, re-downloaded the Organizer, created now Profiles, wiped the Registry but nothing has worked. The Program works fine for DS3 still and I can manually copy and rename the savefiles for the desired effect, so the Files themselves aren't corrupted. I have tried everything that came to my mind so I would really appreciate it if someone knew what I could do, thanks in advance for your troubles.

**Comment by Kahmul** [comment]
This is remaster related issue that has been "addressed" in a recent update, as in the message has been made less intrusive. There is not much to it other than loading a save at the wrong time for remaster that can make the load process fail. Spamming load savefile a few times or making sure you only load in the main menu should be good enough.
